# https://blog.nimblepros.com/blogs/using-workflow-run-in-github-actions/

name: Comment on the Pull Request

# read-write repo token
# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: [".NET Core"]
    types:
      - completed

jobs:
   add-code-coverage-to-pr:
    uses: NimblePros/NimblePros.GitHub.Workflows/.github/workflows/comment-on-pr.yml@main
    with:
      pr-number: ${{ needs.build.outputs.pr-number }}
      code-coverage-artifact-name: ${{ needs.build.outputs.code-coverage-artifact-name }}
      code-coverage-artifact-path: ${{ needs.build.outputs.code-coverage-artifact-path }}    